import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        href="https://fonts.cdnfonts.com/css/space-grotesk"
        rel="stylesheet"
      ></link>
      <body className="bg-[#111827]">
        <div
          className="bg lg:px-20 px-10 mx-auto"
          style={{
            backgroundImage: `url(/bg/bg-element.png)`,
            backgroundSize: "cover",
            backgroundRepeat: "no-repeat",
          }}
        >
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
